<a href="https://colab.research.google.com/github/riadnwu/Algorithms/blob/master/BANSpEmo_BanglaSER_SUBESCO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BANSpEmo_BanglaSER_SUBESCO

#Connect to Google Drive with BANSpEmo_BanglaSER_SUBESCO dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
#!pip install opencv-python==3.4.18.65
!pip install librosa==0.9.2
#!pip install numba==0.48
#!pip install tensorflow==2.8.1
!pip install protobuf==3.20.3


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.1 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.5
    Uninstalling protobuf-4.25.5:
      Successfully uninstalled protobuf-4.25.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.62.3 requires protobuf>=4.21.6, but you have protobuf 3.20.3 which is incompatible.
pandas-gbq 0.24.0 requires google-auth-oauthlib>=0.7.0, but you have google-auth-oauthlib 0.4.6 which is incompatible.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.8.1 which is incompatible.


*# !!! no need to run this section Speech Signal Transformation*

In [ ]:
#Md. Riadul Islam
#2107507
#riadnwu@gmail.com
#09/02/22

#Data Process And save
from numpy.core.fromnumeric import shape
import librosa
import pathlib
import numpy as np
import pandas as pd
import csv
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from librosa import display
import matplotlib.pyplot as plt
import librosa


log_mel_spectrogram =[]

def load_logmel_train_data_with_pca(csv_path,wav_path, n_mels, sr, hop_length):
    # Load the CSV file into a DataFrame
    df = pd.read_csv(csv_path)

    # Define emotion mapping
    emotion_mapping = {
        "ANGRY": 0,
        "DISGUST": 1,
        "FEAR": 2,
        "HAPPY": 3,
        "NEUTRAL": 4,
        "SAD": 5,
        "SURPRISE": 6
    }

    # Initialize lists for features (train_x) and labels (train_y)
    log_mel_spectrograms = []
    train_y = []

    # Assuming correct column names are 'filepath' and 'emotion'
    for idx, row in df.iterrows():
        file_path = row['file_path']  # Adjust this based on the actual column name
        emotion = row['emotion']

        # Load the audio file using librosa
        try:
            print(file_path)
            audio, sr = librosa.load(wav_path+file_path, sr=sr)
            if len(audio) < 176400:
                audio = np.concatenate((audio, np.zeros(176400-len(audio) )), axis=0) #240000,128
            else:
                audio=audio[0:176400]

            # Compute the Mel spectrogram
            mel_spectrogram = librosa.feature.melspectrogram(y=audio, sr=sr, n_mels=n_mels, hop_length=hop_length)

            # Convert the Mel spectrogram to log scale (dB)
            log_mel_spectrogram = librosa.power_to_db(mel_spectrogram, ref=np.max)
            #print(log_mel_spectrogram.shape)

            # Append the log-mel spectrogram to log_mel_spectrograms
            log_mel_spectrograms.append(log_mel_spectrogram.flatten())  # Flatten to 1D for PCA
            train_y.append(emotion_mapping[emotion])  # Append the encoded emotion to train_y

        except Exception as e:
            print(f"Error loading {file_path}: {e}")

    return log_mel_spectrograms, train_y

dataName='SUBESCO'
folder='fold_1_'+dataName

train_path='/content/drive/MyDrive/data/BSER_all_marge/All_5fold_csv/'+dataName+'/train_'+folder+'.csv'
test_path='/content/drive/MyDrive/data/BSER_all_marge/All_5fold_csv/'+dataName+'/test_'+folder+'.csv'
wav_path='/content/drive/MyDrive/data/BSER_all_marge/All_Data/'
# Test the updated function
n_mels=128
sr=44100
hop_length=345 #512


train_x, train_y = load_logmel_train_data_with_pca(train_path,wav_path,n_mels, sr, hop_length)
test_x, test_y = load_logmel_train_data_with_pca(test_path,wav_path,n_mels, sr, hop_length)


# 128 sequences and 512 (i.e., 128000/250) frames for three 2D
#44160 176400/
#n_mels=128, sr=44100, hop_length=512,
x=128 #128
y=512#259#513#513#768 #384 #256 345
z=1


train_data_x = np.array(train_x).reshape(-1, x, y,z,1)
train_data_y = np.array(train_y)

test_data_x = np.array(test_x).reshape(-1, x, y,z,1)
test_data_y = np.array(test_y)


print(train_data_x.shape)




M_ANGRY_SUBESCO_1540.wav
M_ANGRY_SUBESCO_1962.wav
F_ANGRY_SUBESCO_1372.wav
M_ANGRY_SUBESCO_1528.wav
F_ANGRY_SUBESCO_1123.wav
F_ANGRY_SUBESCO_1480.wav
F_ANGRY_SUBESCO_1440.wav
M_ANGRY_SUBESCO_1781.wav
F_ANGRY_SUBESCO_1280.wav
M_ANGRY_SUBESCO_1937.wav
F_ANGRY_SUBESCO_1060.wav
M_ANGRY_SUBESCO_1772.wav
F_ANGRY_SUBESCO_1185.wav
F_ANGRY_SUBESCO_1421.wav
F_ANGRY_SUBESCO_1444.wav
F_ANGRY_SUBESCO_1182.wav
M_HAPPY_SUBESCO_1545.wav
M_HAPPY_SUBESCO_1559.wav
M_HAPPY_SUBESCO_1915.wav
M_ANGRY_SUBESCO_1897.wav
M_ANGRY_SUBESCO_1657.wav
M_ANGRY_SUBESCO_1590.wav
F_HAPPY_SUBESCO_1166.wav
M_ANGRY_SUBESCO_1833.wav
F_ANGRY_SUBESCO_1016.wav
F_ANGRY_SUBESCO_1316.wav
M_HAPPY_SUBESCO_1863.wav
M_HAPPY_SUBESCO_1555.wav
F_HAPPY_SUBESCO_1195.wav
M_ANGRY_SUBESCO_1600.wav
F_HAPPY_SUBESCO_1204.wav
M_HAPPY_SUBESCO_1931.wav
M_ANGRY_SUBESCO_1955.wav
M_HAPPY_SUBESCO_1620.wav
M_HAPPY_SUBESCO_1751.wav
F_FEAR_SUBESCO_1324.wav
F_HAPPY_SUBESCO_1361.wav
M_FEAR_SUBESCO_1975.wav
F_ANGRY_SUBESCO_1388.wav
F_FEAR_SUBESCO_1033.wav
M_A

KeyboardInterrupt: 

# RUN this Section

In [ ]:
import h5py
import pandas as pd
import numpy as np
from numpy.core.fromnumeric import shape
import librosa
import pathlib
import numpy as np
import pandas as pd
import csv
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from librosa import display
import matplotlib.pyplot as plt
import librosa

def find_fold_file(h5_path,csv_path):
    with h5py.File(h5_path, 'r') as hf:
        x = hf['x'][:]        # Load feature data
        y = hf['y'][:]        # Load labels
        file_path_h5 = [x.decode() for x in hf['file_path'][:]]  # Decode file paths

    # Load file paths from the CSV file
    df_csv = pd.read_csv(csv_path)

    # Ensure file path column exists in the CSV file
    if 'file_path' not in df_csv.columns:
        raise KeyError("The column 'file_path' is not found in the CSV file.")

    file_path_csv = df_csv['file_path'].tolist()  # Get file paths from the CSV

    # Match file paths between HDF5 and CSV
    matched_indices = [i for i, path in enumerate(file_path_h5) if path in file_path_csv]


    # Extract matching rows
    x_matched = x[matched_indices]
    y_matched = y[matched_indices]
    #file_path_matched = [file_path_h5[i] for i in matched_indices]
    hf=[]
    x = []      # Load feature data
    y =[]        # Load labels
    file_path_h5 =[]
    matched_indices=[]
    return x_matched,y_matched

dataName='SUBESCO'
folder='fold_1_'+dataName

train_path='/content/drive/MyDrive/data/BSER_all_marge/All_5fold_csv/'+dataName+'/train_'+folder+'.csv'
test_path='/content/drive/MyDrive/data/BSER_all_marge/All_5fold_csv/'+dataName+'/test_'+folder+'.csv'
h5_path='/content/drive/MyDrive/data/BSER_all_marge/All_process_data_hdf5/train_data.h5'
# Test the updated function
n_mels=128
sr=44100
hop_length=345 #512


train_x, train_y = find_fold_file(h5_path,train_path)
test_x, test_y = find_fold_file(h5_path,test_path)


# 128 sequences and 512 (i.e., 128000/250) frames for three 2D
#44160 176400/
#n_mels=128, sr=44100, hop_length=512,
x=128 #128
y=512#259#513#513#768 #384 #256 345
z=1


train_data_x = np.array(train_x).reshape(-1, x, y,z,1)
train_data_y = np.array(train_y)

test_data_x = np.array(test_x).reshape(-1, x, y,z,1)
test_data_y = np.array(test_y)



# DL Model in REIS

In [ ]:
import tensorflow as tf
from tensorflow.keras.utils import normalize, to_categorical
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.model_selection import KFold
import tensorflow as tf
from tensorflow import keras,nn
from tensorflow.keras import layers
import keras.backend as K
from sklearn.model_selection import cross_validate

#3d
def model3d(input_shape, num_classes):

    model = keras.Sequential(name='model3d')

    #LFLB1
    model.add(layers.Conv3D(filters=64,kernel_size=4,strides=1,padding='same',input_shape=input_shape))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling3D(pool_size=(2,2,1), strides=(2,2,1)))

    #LFLB2
    model.add(layers.Conv3D(filters=64,kernel_size=4,strides=1, padding='same', ))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling3D(pool_size=(4,4,1), strides=(4,4,1)))
    #model.add(layers.MaxPooling2D(pool_size=2, strides=2))

    #LFLB3
    model.add(layers.Conv3D(filters=128,kernel_size=4,strides=1,padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling3D(pool_size=(4,4,1), strides=(4,4,1)))
    #model.add(layers.MaxPooling2D(pool_size=2, strides=2))


    #LFLB4
    model.add(layers.Conv3D(filters=128,kernel_size=4,strides=1,padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling3D(pool_size=(4,4,1), strides=(4,4,1)))



    #model.add(layers.Reshape((-1, 128)))
    model.add(layers.TimeDistributed(layers.Flatten()))

    #bi-LSTM
    #model.add(layers.LSTM(256))
    model.add(layers.Bidirectional(layers.LSTM(512)))

    #model.add(keras.layers.Dense(128,activation=nn.relu))
    #model.add(layers.Dense(128,activation=nn.relu))
    model.add(layers.Dense(units=num_classes, activation='softmax'))

    model.summary()

    opt = tf.keras.optimizers.Adam(learning_rate=0.0006, decay=1e-6)

    model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['categorical_accuracy'])

    return model

#2d
def model2d(input_shape, num_classes):

    model = keras.Sequential(name='model2d')

    #LFLB1
    model.add(layers.Conv2D(filters=64,kernel_size=4,strides=1,padding='same',input_shape=input_shape))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling2D(pool_size=2, strides=2))

    #LFLB2
    model.add(layers.Conv2D(filters=64,kernel_size=4,strides=1, padding='same', ))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling2D(pool_size=4, strides=4))
    #model.add(layers.MaxPooling2D(pool_size=2, strides=2))

    #LFLB3
    model.add(layers.Conv2D(filters=128,kernel_size=4,strides=1,padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling2D(pool_size=4, strides=4))
    #model.add(layers.MaxPooling2D(pool_size=2, strides=2))



    #LFLB4
    model.add(layers.Conv2D(filters=128,kernel_size=4,strides=1,padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.MaxPooling2D(pool_size=4, strides=4))

    #model.add(layers.Reshape((-1, 128)))
    model.add(layers.TimeDistributed(layers.Flatten()))

    #LSTM
    #model.add(layers.LSTM(256))
    model.add(layers.Bidirectional(layers.LSTM(512)))

    #model.add(keras.layers.Dense(128,activation=nn.relu))
    #model.add(layers.Dense(128,activation=nn.relu))
    model.add(layers.Dense(units=num_classes, activation='softmax'))

    model.summary()

    opt = keras.optimizers.Adam(learning_rate=0.0006, decay=1e-6)

    model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['categorical_accuracy'])

    return model

def train(train_data_x, train_data_y,test_data_x, test_data_y,emotion,emotionNumber):


  model = model2d(input_shape=(128,512,1), num_classes=emotionNumber)
  #model = model3d(input_shape=(128,513,3,1), num_classes=emotionNumber)
  #model = model2CNN2F(input_shape=(128, 259, 1), num_classes=emotionNumber)
  #model = model4CNNLSTM(input_shape=(128, 513, 3), num_classes=emotionNumber)
  #model = model4CNNBiLSTM(input_shape=(128, 259, 1), num_classes=emotionNumber)
  #model = model7CNN2F(input_shape=(128, 259, 1), num_classes=emotionNumber)

  es = EarlyStopping(monitor='val_categorical_accuracy',mode='max',verbose=1,patience=20)
  mc = ModelCheckpoint(path+'/model/'+folder+'_max_model.h5',monitor='val_categorical_accuracy',mode='max',verbose=1,save_best_only=True)
  history=model.fit(train_data_x, train_data_y,validation_data=(test_data_x, test_data_y),epochs=120,batch_size=10,verbose=2,callbacks=[es,mc])

  model=[]
  acc=history.history['categorical_accuracy']
  vacc=history.history['val_categorical_accuracy']
  loss=history.history['loss']
  vloss=history.history['val_loss']
  accLoss=[]
  accLoss.append(acc)
  accLoss.append(vacc)
  accLoss.append(loss)
  accLoss.append(vloss)
  acc=history.history['categorical_accuracy'][len(history.history['categorical_accuracy']) - 1]
  accLoss=[]
  model=[]
  return acc

def test(test_data_x, test_data_y,emotion):

    new_model = load_model(path+'/model/'+emotion+'_max_model.h5')
    history=new_model.evaluate(test_data_x, test_data_y, batch_size=1)
    predict=new_model.predict(test_data_x)
    return history[1]

def maxIndex(data):
  max=data[0]
  index=0
  for i in range(1,len(data)):
    if(max<data[i]):
      max=data[i]
      index=i
  return index

def test_emotion(test_data_x, test_data_y,total,emotion):

    new_model = load_model(path+'/model/'+emotion+'_max_model.h5')
    #test_data_y=to_categorical(test_data_y)
    history=new_model.evaluate(test_data_x, test_data_y, batch_size=10)
    predict=new_model.predict(test_data_x)
    test_data_y=np.argmax(test_data_y, axis=1)
    temp=total+2
    count=[[0]*temp]*temp
    count=np.array(count)
    #print(count)
    for i in range(0,len(test_data_y)):
      predictNew=maxIndex(predict[i])
      #print(str(test_data_y[i])+' -- '+ str(predictNew))
      #print()
      count[test_data_y[i]][predictNew]=count[test_data_y[i]][predictNew]+1

    for i in range(0,total):
       for j in range(0,total):
        if(i==j):
          count[i][total]=count[i][j]
          count[i][total+1]=sum(count[i][0:total])-count[i][j]
    #count[total][total]=sum(count[total][total]) # corect
    #count[total][total+1]=sum(count[total][total+1]) #miss
    #totalSum=sum(count[0:total][0:total])
    #count[total+1][total+1]= (totalSum-count[total][total+1])/totalSum

    with open(path +'/data/'+emotion+'_confution.csv',"w+") as my_csv:
      csvWriter = csv.writer(my_csv,delimiter=',')
      csvWriter.writerows(count)
    print(count)
    return count




#Single DL Framework for REIS

In [ ]:
#train_data_y = np.array(np.genfromtxt(path +'/data/train_data_y.csv', delimiter=','))
#test_data_y = np.array(np.genfromtxt(path +'/data/test_data_y.csv', delimiter=','))
path='/content/drive/MyDrive/BSER_all_marge'
train_data_y1 = to_categorical(train_data_y)
test_data_y1 = to_categorical(test_data_y)
emotion='9_emotion'

acc=train(train_data_x, train_data_y1,test_data_x, test_data_y1,emotion,7)

emotion='9_emotion'
test_emotion(test_data_x, test_data_y,9,emotion)

Model: "model2d"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 512, 64)      1088      
                                                                 
 batch_normalization (BatchN  (None, 128, 512, 64)     256       
 ormalization)                                                   
                                                                 
 activation (Activation)     (None, 128, 512, 64)      0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 64, 256, 64)      0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 64, 256, 64)       65600     
                                                                 
 batch_normalization_1 (Batc  (None, 64, 256, 64)      256 

#Cascaded DL Framework for REIS: Stage-1

In [ ]:
def lebelTo5(data):
  print(len(data))
  for i in range(len(data)):
    if(int(data[i])%2!=0):
      data[i]=int(data[i])+1
    data[i]=data[i]/2
  return data

train_data_y = np.array(np.genfromtxt(path +'/data/train_data_y.csv', delimiter=','))
test_data_y = np.array(np.genfromtxt(path +'/data/test_data_y.csv', delimiter=','))


train_data_y = to_categorical(lebelTo5(train_data_y))
test_data_y = to_categorical(lebelTo5(test_data_y))

emotion='5_emotion'

acc=train(train_data_x, train_data_y,test_data_x, test_data_y,emotion,5)
test_emotion(test_data_x, test_data_y,5,emotion)

1350
342
Model: "model2d"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 128, 513, 64)      3136      
                                                                 
 batch_normalization_4 (Batc  (None, 128, 513, 64)     256       
 hNormalization)                                                 
                                                                 
 activation_4 (Activation)   (None, 128, 513, 64)      0         
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 64, 256, 64)      0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 64, 256, 64)       65600     
                                                                 
 batch_normalization_5 (Batc  (None, 64, 256, 64) 

array([[33,  1,  3,  0,  1, 33,  5],
       [ 1, 64,  5,  1,  5, 64, 12],
       [ 1,  1, 66,  1,  7, 66, 10],
       [ 0,  3,  1, 70,  2, 70,  6],
       [ 0,  5,  8,  1, 62, 62, 14],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#Cascaded DL Framework for REIS: Stage-2

In [ ]:


def predictTest(test_data_x, test_data_y_5,test_data_y_3,sl):

    new_model = load_model(path+'/model/5_emotion_max_model.h5')
    history=new_model.evaluate((test_data_x), to_categorical(test_data_y_5), batch_size=10)
    predict=new_model.predict((test_data_x))


    tempTestX=[]
    tempTestY=[]
    count=0
    for i in range(len(test_data_y_5)):
      predict_5=maxIndex(predict[i])
      if(predict_5==sl and predict_5==test_data_y_5[i]):
        tempTestX.append(test_data_x[i])
        tempTestY.append(test_data_y_3[i])
        count=count+1
    print(count)
    tempTestX=np.array(tempTestX)
    tempTestY=np.array(tempTestY)


    print(tempTestX.shape)
    print(tempTestY.shape)
    return tempTestX, tempTestY


def labelTo2All(train_data_y,train_data_x,label):
  label=label*2
  tempX=[]
  tempY=[]
  for i in range(len(train_data_y)):
    if(int(train_data_y[i])+1==label):
      tempY.append(0)
      tempX.append(train_data_x[i])
    elif(int(train_data_y[i])== label):
      tempY.append(1)
      tempX.append(train_data_x[i])
    #else:
      #tempY.append(2)
      #tempX.append(train_data_x[i])
  tempX=np.array(tempX)
  tempY=np.array(tempY)
  print(tempX.shape)
  print(tempY.shape)
  return tempX,tempY

def lebelTo5(data):
  print(len(data))
  for i in range(len(data)):
    if(int(data[i])%2!=0):
      data[i]=int(data[i])+1
    data[i]=data[i]/2
  return data
def lebelTo3(train_data_y):

  tempX=[]
  tempY=[]
  for i in range(len(train_data_y)):
    if(int(train_data_y[i])%2==0 and int(train_data_y[i])!=0):
      train_data_y[i]=1
    elif(int(train_data_y[i])!=0):
      train_data_y[i]=0
    else:
      train_data_y[i]=2
  return train_data_y

emotion=['All','happy','sad','angry','fearful']
all=[]
for i in range(1,len(emotion)):
#for i in range(4,5):
  train_data_y = np.array(np.genfromtxt(path +'/data/train_data_y.csv', delimiter=','))
  tempTrainX,tempTrainY=labelTo2All(train_data_y,train_data_x,i)

  test_data_y= np.array(np.genfromtxt(path +'/data/test_data_y.csv', delimiter=','))
  test_data_y_5=lebelTo5(test_data_y)

  test_data_y= np.array(np.genfromtxt(path +'/data/test_data_y.csv', delimiter=','))
  test_data_y_3=lebelTo3(test_data_y)

  tempTestX,tempTestY=predictTest(test_data_x, test_data_y_5,test_data_y_3,i)
  acc=train(tempTrainX, to_categorical(tempTrainY),tempTestX,to_categorical(tempTestY),emotion[i],2)
  all.append(test_emotion(tempTestX, to_categorical(tempTestY),2,emotion[i]))
print(all)


(300, 128, 513, 3, 1)
(300,)
342
35/35 [==============================] - 2s 21ms/step - loss: 0.7176 - categorical_accuracy: 0.8626
64
(64, 128, 513, 3, 1)
(64,)
Model: "model2d"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 128, 513, 64)      3136      
                                                                 
 batch_normalization_8 (Batc  (None, 128, 513, 64)     256       
 hNormalization)                                                 
                                                                 
 activation_8 (Activation)   (None, 128, 513, 64)      0         
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 64, 256, 64)      0         
 2D)                                                             
                                                                 
 conv2d_9 (Conv2D)          

# Test Cascaded DL Framework for REIS

In [ ]:
def maxIndex(data):
  max=data[0]
  index=0
  for i in range(1,len(data)):
    if(max<data[i]):
      max=data[i]
      index=i
  return index

def lebelTo5(data):
  print(len(data))
  for i in range(len(data)):
    if(int(data[i])%2!=0):
      data[i]=int(data[i])+1
    data[i]=data[i]/2
  return data

def labelTo3(train_data_y):

  tempX=[]
  tempY=[]
  for i in range(len(train_data_y)):
    if(int(train_data_y[i])%2==0 and int(train_data_y[i])!=0):
      train_data_y[i]=1
    elif(int(train_data_y[i])!=0):
      train_data_y[i]=0
    #else:
      #train_data_y[i]=2
  return train_data_y

def labelTo2All(train_data_y,train_data_x):

  tempX=[]
  tempY=[]
  for i in range(len(train_data_y)):
    if(int(train_data_y[i])%2==0 and int(train_data_y[i])!=0):
      tempY.append(1)
      tempX.append(train_data_x[i])
    elif(int(train_data_y[i])!=0):
      tempY.append(0)
      tempX.append(train_data_x[i])
    #else:
      #data[i]=2
  tempX=np.array(tempX)
  tempY=np.array(tempY)
  print(tempX.shape)
  print(tempY.shape)
  return tempX,tempY

def test(test_data_x, test_data_y_5,test_data_y_3,emotion,sl):


    new_model = load_model(path+'/model/5_emotion_max_model.h5')
    history=new_model.evaluate((test_data_x), to_categorical(test_data_y_5), batch_size=10)
    predict=new_model.predict((test_data_x))


    tempTestX=[]
    tempTestY=[]
    count=0
    for i in range(len(test_data_y_5)):
      predict_5=maxIndex(predict[i])
      if(predict_5==sl and predict_5==test_data_y_5[i]):
        tempTestX.append(test_data_x[i])
        tempTestY.append(test_data_y_3[i])
        count=count+1
    print(count)

    tempTestY=to_categorical(tempTestY)
    #tempTestX=normalize(tempTestX)
    tempTestX=np.array(tempTestX)
    #test_data_y_3=to_categorical(test_data_y_3)
    test_emotion(tempTestX, tempTestY,2,emotion)
    #new_model = load_model(path+'/model/'+emotion+'_model.h5')
    #history=new_model.evaluate(tempTestX, tempTestY, batch_size=10)



emotion=['natural','happy','sad','angry','fearful']

#path = '/content/drive/Othercomputers/My Laptop 07-10-2021/MSc KUET/Thesis/Dataset/RAVDESS/All'
path='/content/drive/MyDrive/MSc KUET/Thesis/Dataset/RAVDESS/All'
#path='/content/drive/MyDrive/MSc KUET/Thesis/Dataset/RAVDESS/Song+Speech/Actor_02'
#test_data_x = np.array(np.genfromtxt(path +'/data/test_data_x.csv', delimiter=',')).reshape(-1, 128, 256, 3)
for i in range(1,5):
  test_data_y = np.array(np.genfromtxt(path +'/data/test_data_y.csv', delimiter=','))

  test_data_y_5 = lebelTo5(test_data_y)
  test_data_y = np.array(np.genfromtxt(path +'/data/test_data_y.csv', delimiter=','))
  test_data_y_3=labelTo3(test_data_y)


  test(test_data_x, test_data_y_5,test_data_y_3,emotion[i],i)
  #test(test_data_x, test_data_y_5,test_data_y_3,'All',i)

342
11/11 [==============================] - 1s 43ms/step
66
3/3 [==============================] - 1s 31ms/step
[[27  4 27  4]
 [ 2 33 33  2]
 [ 0  0  0  0]
 [ 0  0  0  0]]
342
11/11 [==============================] - 2s 45ms/step
65
3/3 [==============================] - 1s 31ms/step
[[29  3 29  3]
 [ 3 30 30  3]
 [ 0  0  0  0]
 [ 0  0  0  0]]
342
11/11 [==============================] - 1s 44ms/step
70
3/3 [==============================] - 1s 33ms/step
[[31  2 31  2]
 [ 1 36 36  1]
 [ 0  0  0  0]
 [ 0  0  0  0]]
342
11/11 [==============================] - 1s 44ms/step
55
2/2 [==============================] - 1s 14ms/step
[[25  0 25  0]
 [ 0 30 30  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
